#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

echo "[🐶] Husky is smelling your commit ..."

# List all the commands you want to run here
commands=(
  # "git rm -rf --cached --ignore-unmatch .env"
  "npx prettier@latest . --write"
  "yarn nx run-many --target=lint --all=true",
  # "yarn build",
  "git add ."
  # Add more commands if needed
)

# Create a temporary log file
log_file="$(dirname -- "$0")/husky.debug.log"
[ -f "$log_file" ] && rm "$log_file"
touch "$log_file"

# Redirect all output to the log file (except "good to go" message)
exec 6>&1 4>&2 1>"$log_file" 2>&1

# Function to display a loading animation
show_loading_animation() {
  pid="$1"
  delay=0.1
  i=1
  spinner="/-\|"

  while [ -d "/proc/$pid" ]; do
    printf "\r%s" "${spinner:$i:1}"
    sleep "$delay"
    i=$(( (i + 1) % 4 ))
  done
  printf "\r"
}

# Variable to track whether an error occurred during the commands' execution
has_error=false

# Iterate over each command and run them with the loading animation
for cmd in "${commands[@]}"; do
  echo "[🐶] Starting new command ..."
  echo "[🐶] Digging 🐾 $cmd 🐾" >&6
  sh -c "$cmd" 2>&1 | tee -a "$log_file"
  cmd_exit_code=${PIPESTATUS[0]}

  # If a command exits with a non-zero status code, print "there is an error" and set the error flag
  if [ "$cmd_exit_code" -ne 0 ]; then
    has_error=true
    echo "[🐶] $cmd ended with $cmd_exit_code ☠️" >&6
  fi
done

# Restore the standard output and error
exec 1>&6 2>&4

if [ "$has_error" = true ]; then
  # Error occurred, display log file and exit with an error code
  echo "[🐶] 📜 ./.husky/husky.debug.log"
#   cat "$log_file" >&6
#   rm "$log_file"
  grep -i -B 1 "error" "$log_file"
  exit 1
fi

# All commands executed successfully
echo "[🐶] checked and committed ✅"

# Delete the log file as all commands executed successfully
rm "$log_file"

exit 0
